/*
 * generated by Xtext 2.12.0
 */
package org.xtext.trabalho.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MALAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/trabalho/parser/antlr/internal/InternalMAL.tokens");
	}
}
