/*
 * generated by Xtext 2.12.0
 */
package org.xtext.trabalho.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.trabalho.parser.antlr.internal.InternalMALParser;
import org.xtext.trabalho.services.MALGrammarAccess;

public class MALParser extends AbstractAntlrParser {

	@Inject
	private MALGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMALParser createParser(XtextTokenStream stream) {
		return new InternalMALParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}

	public MALGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MALGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
