/*
 * generated by Xtext 2.12.0
 */
package org.xtext.trabalho.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.xtext.trabalho.MALRuntimeModule
import org.xtext.trabalho.MALStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class MALIdeSetup extends MALStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new MALRuntimeModule, new MALIdeModule))
	}
	
}
