/**
 * generated by Xtext 2.12.0
 */
package org.xtext.trabalho.ui.contentassist;

import org.xtext.trabalho.ui.contentassist.AbstractMALProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class MALProposalProvider extends AbstractMALProposalProvider {
}
