/*
 * generated by Xtext 2.12.0
 */
package org.xtext.trabalho.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.trabalho.mal.ui.internal.MalActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MALExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return MalActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return MalActivator.getInstance().getInjector(MalActivator.ORG_XTEXT_TRABALHO_MAL);
	}
	
}
