/**
 * generated by Xtext 2.12.0
 */
package org.xtext.trabalho.mAL.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.trabalho.mAL.Fcncall;
import org.xtext.trabalho.mAL.MALPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Fcncall</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class FcncallImpl extends ExprImpl implements Fcncall
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FcncallImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MALPackage.Literals.FCNCALL;
  }

} //FcncallImpl
