/**
 * generated by Xtext 2.12.0
 */
package org.xtext.trabalho.mAL.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.trabalho.mAL.MALPackage;
import org.xtext.trabalho.mAL.ModuleStmt;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Module Stmt</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.trabalho.mAL.impl.ModuleStmtImpl#isHelp <em>Help</em>}</li>
 *   <li>{@link org.xtext.trabalho.mAL.impl.ModuleStmtImpl#getIdent <em>Ident</em>}</li>
 *   <li>{@link org.xtext.trabalho.mAL.impl.ModuleStmtImpl#isSecond_ident <em>Second ident</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ModuleStmtImpl extends StatementImpl implements ModuleStmt
{
  /**
   * The default value of the '{@link #isHelp() <em>Help</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isHelp()
   * @generated
   * @ordered
   */
  protected static final boolean HELP_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isHelp() <em>Help</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isHelp()
   * @generated
   * @ordered
   */
  protected boolean help = HELP_EDEFAULT;

  /**
   * The default value of the '{@link #getIdent() <em>Ident</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIdent()
   * @generated
   * @ordered
   */
  protected static final String IDENT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getIdent() <em>Ident</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIdent()
   * @generated
   * @ordered
   */
  protected String ident = IDENT_EDEFAULT;

  /**
   * The default value of the '{@link #isSecond_ident() <em>Second ident</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isSecond_ident()
   * @generated
   * @ordered
   */
  protected static final boolean SECOND_IDENT_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isSecond_ident() <em>Second ident</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isSecond_ident()
   * @generated
   * @ordered
   */
  protected boolean second_ident = SECOND_IDENT_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ModuleStmtImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MALPackage.Literals.MODULE_STMT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public boolean isHelp()
  {
    return help;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setHelp(boolean newHelp)
  {
    boolean oldHelp = help;
    help = newHelp;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MALPackage.MODULE_STMT__HELP, oldHelp, help));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getIdent()
  {
    return ident;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setIdent(String newIdent)
  {
    String oldIdent = ident;
    ident = newIdent;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MALPackage.MODULE_STMT__IDENT, oldIdent, ident));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public boolean isSecond_ident()
  {
    return second_ident;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSecond_ident(boolean newSecond_ident)
  {
    boolean oldSecond_ident = second_ident;
    second_ident = newSecond_ident;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MALPackage.MODULE_STMT__SECOND_IDENT, oldSecond_ident, second_ident));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MALPackage.MODULE_STMT__HELP:
        return isHelp();
      case MALPackage.MODULE_STMT__IDENT:
        return getIdent();
      case MALPackage.MODULE_STMT__SECOND_IDENT:
        return isSecond_ident();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MALPackage.MODULE_STMT__HELP:
        setHelp((Boolean)newValue);
        return;
      case MALPackage.MODULE_STMT__IDENT:
        setIdent((String)newValue);
        return;
      case MALPackage.MODULE_STMT__SECOND_IDENT:
        setSecond_ident((Boolean)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MALPackage.MODULE_STMT__HELP:
        setHelp(HELP_EDEFAULT);
        return;
      case MALPackage.MODULE_STMT__IDENT:
        setIdent(IDENT_EDEFAULT);
        return;
      case MALPackage.MODULE_STMT__SECOND_IDENT:
        setSecond_ident(SECOND_IDENT_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MALPackage.MODULE_STMT__HELP:
        return help != HELP_EDEFAULT;
      case MALPackage.MODULE_STMT__IDENT:
        return IDENT_EDEFAULT == null ? ident != null : !IDENT_EDEFAULT.equals(ident);
      case MALPackage.MODULE_STMT__SECOND_IDENT:
        return second_ident != SECOND_IDENT_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (help: ");
    result.append(help);
    result.append(", ident: ");
    result.append(ident);
    result.append(", second_ident: ");
    result.append(second_ident);
    result.append(')');
    return result.toString();
  }

} //ModuleStmtImpl
