/**
 * generated by Xtext 2.12.0
 */
package org.xtext.trabalho.mAL.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.trabalho.mAL.Helpinfo;
import org.xtext.trabalho.mAL.MALPackage;
import org.xtext.trabalho.mAL.ModuleStmt;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Module Stmt</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.trabalho.mAL.impl.ModuleStmtImpl#getHelp <em>Help</em>}</li>
 *   <li>{@link org.xtext.trabalho.mAL.impl.ModuleStmtImpl#getIdent <em>Ident</em>}</li>
 *   <li>{@link org.xtext.trabalho.mAL.impl.ModuleStmtImpl#getIdent1 <em>Ident1</em>}</li>
 *   <li>{@link org.xtext.trabalho.mAL.impl.ModuleStmtImpl#getIdent2 <em>Ident2</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ModuleStmtImpl extends StatementImpl implements ModuleStmt
{
  /**
   * The cached value of the '{@link #getHelp() <em>Help</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHelp()
   * @generated
   * @ordered
   */
  protected Helpinfo help;

  /**
   * The default value of the '{@link #getIdent() <em>Ident</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIdent()
   * @generated
   * @ordered
   */
  protected static final String IDENT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getIdent() <em>Ident</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIdent()
   * @generated
   * @ordered
   */
  protected String ident = IDENT_EDEFAULT;

  /**
   * The default value of the '{@link #getIdent1() <em>Ident1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIdent1()
   * @generated
   * @ordered
   */
  protected static final String IDENT1_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getIdent1() <em>Ident1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIdent1()
   * @generated
   * @ordered
   */
  protected String ident1 = IDENT1_EDEFAULT;

  /**
   * The default value of the '{@link #getIdent2() <em>Ident2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIdent2()
   * @generated
   * @ordered
   */
  protected static final String IDENT2_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getIdent2() <em>Ident2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIdent2()
   * @generated
   * @ordered
   */
  protected String ident2 = IDENT2_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ModuleStmtImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MALPackage.Literals.MODULE_STMT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Helpinfo getHelp()
  {
    return help;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetHelp(Helpinfo newHelp, NotificationChain msgs)
  {
    Helpinfo oldHelp = help;
    help = newHelp;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MALPackage.MODULE_STMT__HELP, oldHelp, newHelp);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setHelp(Helpinfo newHelp)
  {
    if (newHelp != help)
    {
      NotificationChain msgs = null;
      if (help != null)
        msgs = ((InternalEObject)help).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MALPackage.MODULE_STMT__HELP, null, msgs);
      if (newHelp != null)
        msgs = ((InternalEObject)newHelp).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MALPackage.MODULE_STMT__HELP, null, msgs);
      msgs = basicSetHelp(newHelp, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MALPackage.MODULE_STMT__HELP, newHelp, newHelp));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getIdent()
  {
    return ident;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setIdent(String newIdent)
  {
    String oldIdent = ident;
    ident = newIdent;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MALPackage.MODULE_STMT__IDENT, oldIdent, ident));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getIdent1()
  {
    return ident1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setIdent1(String newIdent1)
  {
    String oldIdent1 = ident1;
    ident1 = newIdent1;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MALPackage.MODULE_STMT__IDENT1, oldIdent1, ident1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getIdent2()
  {
    return ident2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setIdent2(String newIdent2)
  {
    String oldIdent2 = ident2;
    ident2 = newIdent2;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MALPackage.MODULE_STMT__IDENT2, oldIdent2, ident2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MALPackage.MODULE_STMT__HELP:
        return basicSetHelp(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MALPackage.MODULE_STMT__HELP:
        return getHelp();
      case MALPackage.MODULE_STMT__IDENT:
        return getIdent();
      case MALPackage.MODULE_STMT__IDENT1:
        return getIdent1();
      case MALPackage.MODULE_STMT__IDENT2:
        return getIdent2();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MALPackage.MODULE_STMT__HELP:
        setHelp((Helpinfo)newValue);
        return;
      case MALPackage.MODULE_STMT__IDENT:
        setIdent((String)newValue);
        return;
      case MALPackage.MODULE_STMT__IDENT1:
        setIdent1((String)newValue);
        return;
      case MALPackage.MODULE_STMT__IDENT2:
        setIdent2((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MALPackage.MODULE_STMT__HELP:
        setHelp((Helpinfo)null);
        return;
      case MALPackage.MODULE_STMT__IDENT:
        setIdent(IDENT_EDEFAULT);
        return;
      case MALPackage.MODULE_STMT__IDENT1:
        setIdent1(IDENT1_EDEFAULT);
        return;
      case MALPackage.MODULE_STMT__IDENT2:
        setIdent2(IDENT2_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MALPackage.MODULE_STMT__HELP:
        return help != null;
      case MALPackage.MODULE_STMT__IDENT:
        return IDENT_EDEFAULT == null ? ident != null : !IDENT_EDEFAULT.equals(ident);
      case MALPackage.MODULE_STMT__IDENT1:
        return IDENT1_EDEFAULT == null ? ident1 != null : !IDENT1_EDEFAULT.equals(ident1);
      case MALPackage.MODULE_STMT__IDENT2:
        return IDENT2_EDEFAULT == null ? ident2 != null : !IDENT2_EDEFAULT.equals(ident2);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (ident: ");
    result.append(ident);
    result.append(", ident1: ");
    result.append(ident1);
    result.append(", ident2: ");
    result.append(ident2);
    result.append(')');
    return result.toString();
  }

} //ModuleStmtImpl
