/**
 * generated by Xtext 2.12.0
 */
package org.xtext.trabalho.mAL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Any Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.trabalho.mAL.AnyType#getDigit <em>Digit</em>}</li>
 * </ul>
 *
 * @see org.xtext.trabalho.mAL.MALPackage#getAnyType()
 * @model
 * @generated
 */
public interface AnyType extends EObject
{
  /**
   * Returns the value of the '<em><b>Digit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Digit</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Digit</em>' attribute.
   * @see #setDigit(String)
   * @see org.xtext.trabalho.mAL.MALPackage#getAnyType_Digit()
   * @model
   * @generated
   */
  String getDigit();

  /**
   * Sets the value of the '{@link org.xtext.trabalho.mAL.AnyType#getDigit <em>Digit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Digit</em>' attribute.
   * @see #getDigit()
   * @generated
   */
  void setDigit(String value);

} // AnyType
