/**
 * generated by Xtext 2.12.0
 */
package org.xtext.trabalho.mAL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Args</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.trabalho.mAL.MALPackage#getArgs()
 * @model
 * @generated
 */
public interface Args extends EObject
{
} // Args
