/**
 * generated by Xtext 2.12.0
 */
package org.xtext.trabalho.mAL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Column Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.trabalho.mAL.MALPackage#getColumnType()
 * @model
 * @generated
 */
public interface ColumnType extends TypeName
{
} // ColumnType
