/**
 * generated by Xtext 2.12.0
 */
package org.xtext.trabalho.mAL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.trabalho.mAL.Definition#getHelp <em>Help</em>}</li>
 * </ul>
 *
 * @see org.xtext.trabalho.mAL.MALPackage#getDefinition()
 * @model
 * @generated
 */
public interface Definition extends Statement
{
  /**
   * Returns the value of the '<em><b>Help</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Help</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Help</em>' containment reference.
   * @see #setHelp(Helpinfo)
   * @see org.xtext.trabalho.mAL.MALPackage#getDefinition_Help()
   * @model containment="true"
   * @generated
   */
  Helpinfo getHelp();

  /**
   * Sets the value of the '{@link org.xtext.trabalho.mAL.Definition#getHelp <em>Help</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Help</em>' containment reference.
   * @see #getHelp()
   * @generated
   */
  void setHelp(Helpinfo value);

} // Definition
