/**
 * generated by Xtext 2.12.0
 */
package org.xtext.trabalho.mAL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Factor</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.trabalho.mAL.Factor#getOperator <em>Operator</em>}</li>
 *   <li>{@link org.xtext.trabalho.mAL.Factor#getLiteral_constant <em>Literal constant</em>}</li>
 *   <li>{@link org.xtext.trabalho.mAL.Factor#getVar <em>Var</em>}</li>
 * </ul>
 *
 * @see org.xtext.trabalho.mAL.MALPackage#getFactor()
 * @model
 * @generated
 */
public interface Factor extends Expr, Args
{
  /**
   * Returns the value of the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Operator</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operator</em>' attribute.
   * @see #setOperator(String)
   * @see org.xtext.trabalho.mAL.MALPackage#getFactor_Operator()
   * @model
   * @generated
   */
  String getOperator();

  /**
   * Sets the value of the '{@link org.xtext.trabalho.mAL.Factor#getOperator <em>Operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operator</em>' attribute.
   * @see #getOperator()
   * @generated
   */
  void setOperator(String value);

  /**
   * Returns the value of the '<em><b>Literal constant</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Literal constant</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Literal constant</em>' attribute.
   * @see #setLiteral_constant(String)
   * @see org.xtext.trabalho.mAL.MALPackage#getFactor_Literal_constant()
   * @model
   * @generated
   */
  String getLiteral_constant();

  /**
   * Sets the value of the '{@link org.xtext.trabalho.mAL.Factor#getLiteral_constant <em>Literal constant</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Literal constant</em>' attribute.
   * @see #getLiteral_constant()
   * @generated
   */
  void setLiteral_constant(String value);

  /**
   * Returns the value of the '<em><b>Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Var</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var</em>' attribute.
   * @see #setVar(String)
   * @see org.xtext.trabalho.mAL.MALPackage#getFactor_Var()
   * @model
   * @generated
   */
  String getVar();

  /**
   * Sets the value of the '{@link org.xtext.trabalho.mAL.Factor#getVar <em>Var</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var</em>' attribute.
   * @see #getVar()
   * @generated
   */
  void setVar(String value);

} // Factor
