/**
 * generated by Xtext 2.12.0
 */
package org.xtext.trabalho.mAL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Header</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.trabalho.mAL.Header#getHeader_name <em>Header name</em>}</li>
 *   <li>{@link org.xtext.trabalho.mAL.Header#getParams <em>Params</em>}</li>
 *   <li>{@link org.xtext.trabalho.mAL.Header#getReturn_type <em>Return type</em>}</li>
 * </ul>
 *
 * @see org.xtext.trabalho.mAL.MALPackage#getHeader()
 * @model
 * @generated
 */
public interface Header extends EObject
{
  /**
   * Returns the value of the '<em><b>Header name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Header name</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Header name</em>' containment reference.
   * @see #setHeader_name(Name)
   * @see org.xtext.trabalho.mAL.MALPackage#getHeader_Header_name()
   * @model containment="true"
   * @generated
   */
  Name getHeader_name();

  /**
   * Sets the value of the '{@link org.xtext.trabalho.mAL.Header#getHeader_name <em>Header name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Header name</em>' containment reference.
   * @see #getHeader_name()
   * @generated
   */
  void setHeader_name(Name value);

  /**
   * Returns the value of the '<em><b>Params</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Params</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Params</em>' containment reference.
   * @see #setParams(Params)
   * @see org.xtext.trabalho.mAL.MALPackage#getHeader_Params()
   * @model containment="true"
   * @generated
   */
  Params getParams();

  /**
   * Sets the value of the '{@link org.xtext.trabalho.mAL.Header#getParams <em>Params</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Params</em>' containment reference.
   * @see #getParams()
   * @generated
   */
  void setParams(Params value);

  /**
   * Returns the value of the '<em><b>Return type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Return type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Return type</em>' containment reference.
   * @see #setReturn_type(Result)
   * @see org.xtext.trabalho.mAL.MALPackage#getHeader_Return_type()
   * @model containment="true"
   * @generated
   */
  Result getReturn_type();

  /**
   * Sets the value of the '{@link org.xtext.trabalho.mAL.Header#getReturn_type <em>Return type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Return type</em>' containment reference.
   * @see #getReturn_type()
   * @generated
   */
  void setReturn_type(Result value);

} // Header
