/**
 * generated by Xtext 2.12.0
 */
package org.xtext.trabalho.mAL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Module Stmt</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.trabalho.mAL.ModuleStmt#getHelp <em>Help</em>}</li>
 *   <li>{@link org.xtext.trabalho.mAL.ModuleStmt#getIdent <em>Ident</em>}</li>
 * </ul>
 *
 * @see org.xtext.trabalho.mAL.MALPackage#getModuleStmt()
 * @model
 * @generated
 */
public interface ModuleStmt extends Statement
{
  /**
   * Returns the value of the '<em><b>Help</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Help</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Help</em>' containment reference.
   * @see #setHelp(Helpinfo)
   * @see org.xtext.trabalho.mAL.MALPackage#getModuleStmt_Help()
   * @model containment="true"
   * @generated
   */
  Helpinfo getHelp();

  /**
   * Sets the value of the '{@link org.xtext.trabalho.mAL.ModuleStmt#getHelp <em>Help</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Help</em>' containment reference.
   * @see #getHelp()
   * @generated
   */
  void setHelp(Helpinfo value);

  /**
   * Returns the value of the '<em><b>Ident</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ident</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ident</em>' attribute.
   * @see #setIdent(String)
   * @see org.xtext.trabalho.mAL.MALPackage#getModuleStmt_Ident()
   * @model
   * @generated
   */
  String getIdent();

  /**
   * Sets the value of the '{@link org.xtext.trabalho.mAL.ModuleStmt#getIdent <em>Ident</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ident</em>' attribute.
   * @see #getIdent()
   * @generated
   */
  void setIdent(String value);

} // ModuleStmt
