/**
 * generated by Xtext 2.12.0
 */
package org.xtext.trabalho.mAL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Params</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.trabalho.mAL.MALPackage#getParams()
 * @model
 * @generated
 */
public interface Params extends Result
{
} // Params
