/**
 * generated by Xtext 2.12.0
 */
package org.xtext.trabalho.mAL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Varlist</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.trabalho.mAL.Varlist#getVariables <em>Variables</em>}</li>
 * </ul>
 *
 * @see org.xtext.trabalho.mAL.MALPackage#getVarlist()
 * @model
 * @generated
 */
public interface Varlist extends EObject
{
  /**
   * Returns the value of the '<em><b>Variables</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.trabalho.mAL.Variable}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Variables</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variables</em>' containment reference list.
   * @see org.xtext.trabalho.mAL.MALPackage#getVarlist_Variables()
   * @model containment="true"
   * @generated
   */
  EList<Variable> getVariables();

} // Varlist
