/*
 * generated by Xtext 2.12.0
 */
package org.xtext.trabalho.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MALGrammarAccess extends AbstractGrammarElementFinder {
	
	public class ProgramElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.trabalho.MAL.Program");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cElementsAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cElementsStatementParserRuleCall_0_0 = (RuleCall)cElementsAssignment_0.eContents().get(0);
		private final Keyword cSemicolonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//Program:
		//	(elements+=Statement ';')*;
		@Override public ParserRule getRule() { return rule; }
		
		//(elements+=Statement ';')*
		public Group getGroup() { return cGroup; }
		
		//elements+=Statement
		public Assignment getElementsAssignment_0() { return cElementsAssignment_0; }
		
		//Statement
		public RuleCall getElementsStatementParserRuleCall_0_0() { return cElementsStatementParserRuleCall_0_0; }
		
		//';'
		public Keyword getSemicolonKeyword_1() { return cSemicolonKeyword_1; }
	}
	public class StatementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.trabalho.MAL.Statement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final RuleCall cModuleStmtParserRuleCall_0_0 = (RuleCall)cGroup_0.eContents().get(0);
		private final Assignment cHelpAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cHelpHelpinfoParserRuleCall_0_1_0 = (RuleCall)cHelpAssignment_0_1.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final RuleCall cDefinitionParserRuleCall_1_0 = (RuleCall)cGroup_1.eContents().get(0);
		private final Assignment cHelpAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cHelpHelpinfoParserRuleCall_1_1_0 = (RuleCall)cHelpAssignment_1_1.eContents().get(0);
		private final RuleCall cIncludeStmtParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cStmtParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//Statement:
		//	ModuleStmt help=Helpinfo? | Definition help=Helpinfo? | IncludeStmt | Stmt;
		@Override public ParserRule getRule() { return rule; }
		
		//ModuleStmt help=Helpinfo? | Definition help=Helpinfo? | IncludeStmt | Stmt
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//ModuleStmt help=Helpinfo?
		public Group getGroup_0() { return cGroup_0; }
		
		//ModuleStmt
		public RuleCall getModuleStmtParserRuleCall_0_0() { return cModuleStmtParserRuleCall_0_0; }
		
		//help=Helpinfo?
		public Assignment getHelpAssignment_0_1() { return cHelpAssignment_0_1; }
		
		//Helpinfo
		public RuleCall getHelpHelpinfoParserRuleCall_0_1_0() { return cHelpHelpinfoParserRuleCall_0_1_0; }
		
		//Definition help=Helpinfo?
		public Group getGroup_1() { return cGroup_1; }
		
		//Definition
		public RuleCall getDefinitionParserRuleCall_1_0() { return cDefinitionParserRuleCall_1_0; }
		
		//help=Helpinfo?
		public Assignment getHelpAssignment_1_1() { return cHelpAssignment_1_1; }
		
		//Helpinfo
		public RuleCall getHelpHelpinfoParserRuleCall_1_1_0() { return cHelpHelpinfoParserRuleCall_1_1_0; }
		
		//IncludeStmt
		public RuleCall getIncludeStmtParserRuleCall_2() { return cIncludeStmtParserRuleCall_2; }
		
		//Stmt
		public RuleCall getStmtParserRuleCall_3() { return cStmtParserRuleCall_3; }
	}
	public class ModuleStmtElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.trabalho.MAL.ModuleStmt");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cMODULEKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Assignment cIdentAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cIdentIDTerminalRuleCall_0_1_0 = (RuleCall)cIdentAssignment_0_1.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cATOMKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cIdent1Assignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cIdent1IDTerminalRuleCall_1_1_0 = (RuleCall)cIdent1Assignment_1_1.eContents().get(0);
		private final Group cGroup_1_2 = (Group)cGroup_1.eContents().get(2);
		private final Keyword cColonKeyword_1_2_0 = (Keyword)cGroup_1_2.eContents().get(0);
		private final Assignment cIdent2Assignment_1_2_1 = (Assignment)cGroup_1_2.eContents().get(1);
		private final RuleCall cIdent2IDTerminalRuleCall_1_2_1_0 = (RuleCall)cIdent2Assignment_1_2_1.eContents().get(0);
		
		//ModuleStmt:
		//	'MODULE' ident=ID | 'ATOM' ident1=ID (':' ident2=ID)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'MODULE' ident=ID | 'ATOM' ident1=ID (':' ident2=ID)?
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'MODULE' ident=ID
		public Group getGroup_0() { return cGroup_0; }
		
		//'MODULE'
		public Keyword getMODULEKeyword_0_0() { return cMODULEKeyword_0_0; }
		
		//ident=ID
		public Assignment getIdentAssignment_0_1() { return cIdentAssignment_0_1; }
		
		//ID
		public RuleCall getIdentIDTerminalRuleCall_0_1_0() { return cIdentIDTerminalRuleCall_0_1_0; }
		
		//'ATOM' ident1=ID (':' ident2=ID)?
		public Group getGroup_1() { return cGroup_1; }
		
		//'ATOM'
		public Keyword getATOMKeyword_1_0() { return cATOMKeyword_1_0; }
		
		//ident1=ID
		public Assignment getIdent1Assignment_1_1() { return cIdent1Assignment_1_1; }
		
		//ID
		public RuleCall getIdent1IDTerminalRuleCall_1_1_0() { return cIdent1IDTerminalRuleCall_1_1_0; }
		
		//(':' ident2=ID)?
		public Group getGroup_1_2() { return cGroup_1_2; }
		
		//':'
		public Keyword getColonKeyword_1_2_0() { return cColonKeyword_1_2_0; }
		
		//ident2=ID
		public Assignment getIdent2Assignment_1_2_1() { return cIdent2Assignment_1_2_1; }
		
		//ID
		public RuleCall getIdent2IDTerminalRuleCall_1_2_1_0() { return cIdent2IDTerminalRuleCall_1_2_1_0; }
	}
	public class IncludeStmtElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.trabalho.MAL.IncludeStmt");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cINCLUDEKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Assignment cIdentifierAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cIdentifierIDTerminalRuleCall_0_1_0 = (RuleCall)cIdentifierAssignment_0_1.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cINCLUDEKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cString_literalAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cString_literalSTRINGTerminalRuleCall_1_1_0 = (RuleCall)cString_literalAssignment_1_1.eContents().get(0);
		
		//IncludeStmt:
		//	'INCLUDE' identifier=ID | 'INCLUDE' string_literal=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//'INCLUDE' identifier=ID | 'INCLUDE' string_literal=STRING
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'INCLUDE' identifier=ID
		public Group getGroup_0() { return cGroup_0; }
		
		//'INCLUDE'
		public Keyword getINCLUDEKeyword_0_0() { return cINCLUDEKeyword_0_0; }
		
		//identifier=ID
		public Assignment getIdentifierAssignment_0_1() { return cIdentifierAssignment_0_1; }
		
		//ID
		public RuleCall getIdentifierIDTerminalRuleCall_0_1_0() { return cIdentifierIDTerminalRuleCall_0_1_0; }
		
		//'INCLUDE' string_literal=STRING
		public Group getGroup_1() { return cGroup_1; }
		
		//'INCLUDE'
		public Keyword getINCLUDEKeyword_1_0() { return cINCLUDEKeyword_1_0; }
		
		//string_literal=STRING
		public Assignment getString_literalAssignment_1_1() { return cString_literalAssignment_1_1; }
		
		//STRING
		public RuleCall getString_literalSTRINGTerminalRuleCall_1_1_0() { return cString_literalSTRINGTerminalRuleCall_1_1_0; }
	}
	public class DefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.trabalho.MAL.Definition");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cUNSAFEKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Keyword cCOMMANDKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final RuleCall cHeaderParserRuleCall_0_2 = (RuleCall)cGroup_0.eContents().get(2);
		private final Keyword cADDRESSKeyword_0_3 = (Keyword)cGroup_0.eContents().get(3);
		private final Assignment cIdentifierAssignment_0_4 = (Assignment)cGroup_0.eContents().get(4);
		private final RuleCall cIdentifierIDTerminalRuleCall_0_4_0 = (RuleCall)cIdentifierAssignment_0_4.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cUNSAFEKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Keyword cPATTERNKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final RuleCall cHeaderParserRuleCall_1_2 = (RuleCall)cGroup_1.eContents().get(2);
		private final Keyword cADDRESSKeyword_1_3 = (Keyword)cGroup_1.eContents().get(3);
		private final Assignment cIdentifierAssignment_1_4 = (Assignment)cGroup_1.eContents().get(4);
		private final RuleCall cIdentifierIDTerminalRuleCall_1_4_0 = (RuleCall)cIdentifierAssignment_1_4.eContents().get(0);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Alternatives cAlternatives_2_0 = (Alternatives)cGroup_2.eContents().get(0);
		private final Keyword cINLINEKeyword_2_0_0 = (Keyword)cAlternatives_2_0.eContents().get(0);
		private final Keyword cUNSAFEKeyword_2_0_1 = (Keyword)cAlternatives_2_0.eContents().get(1);
		private final Keyword cFUNCTIONKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final RuleCall cHeaderParserRuleCall_2_2 = (RuleCall)cGroup_2.eContents().get(2);
		private final Assignment cStm1Assignment_2_3 = (Assignment)cGroup_2.eContents().get(3);
		private final RuleCall cStm1StatementParserRuleCall_2_3_0 = (RuleCall)cStm1Assignment_2_3.eContents().get(0);
		private final Keyword cENDKeyword_2_4 = (Keyword)cGroup_2.eContents().get(4);
		private final Assignment cNameAssignment_2_5 = (Assignment)cGroup_2.eContents().get(5);
		private final RuleCall cNameNameParserRuleCall_2_5_0 = (RuleCall)cNameAssignment_2_5.eContents().get(0);
		private final Group cGroup_3 = (Group)cAlternatives.eContents().get(3);
		private final Keyword cFACTORYKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final RuleCall cHeaderParserRuleCall_3_1 = (RuleCall)cGroup_3.eContents().get(1);
		private final Assignment cStm2Assignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cStm2StatementParserRuleCall_3_2_0 = (RuleCall)cStm2Assignment_3_2.eContents().get(0);
		private final Keyword cENDKeyword_3_3 = (Keyword)cGroup_3.eContents().get(3);
		private final Assignment cNameAssignment_3_4 = (Assignment)cGroup_3.eContents().get(4);
		private final RuleCall cNameNameParserRuleCall_3_4_0 = (RuleCall)cNameAssignment_3_4.eContents().get(0);
		
		//Definition:
		//	'UNSAFE'? 'COMMAND' Header 'ADDRESS' identifier=ID | 'UNSAFE'? 'PATTERN' Header 'ADDRESS' identifier=ID | ('INLINE' |
		//	'UNSAFE')? 'FUNCTION' Header stm1+=Statement* 'END' name=Name |
		//	'FACTORY' Header stm2+=Statement* 'END' name=Name;
		@Override public ParserRule getRule() { return rule; }
		
		//'UNSAFE'? 'COMMAND' Header 'ADDRESS' identifier=ID | 'UNSAFE'? 'PATTERN' Header 'ADDRESS' identifier=ID | ('INLINE' |
		//'UNSAFE')? 'FUNCTION' Header stm1+=Statement* 'END' name=Name | 'FACTORY' Header stm2+=Statement* 'END' name=Name
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'UNSAFE'? 'COMMAND' Header 'ADDRESS' identifier=ID
		public Group getGroup_0() { return cGroup_0; }
		
		//'UNSAFE'?
		public Keyword getUNSAFEKeyword_0_0() { return cUNSAFEKeyword_0_0; }
		
		//'COMMAND'
		public Keyword getCOMMANDKeyword_0_1() { return cCOMMANDKeyword_0_1; }
		
		//Header
		public RuleCall getHeaderParserRuleCall_0_2() { return cHeaderParserRuleCall_0_2; }
		
		//'ADDRESS'
		public Keyword getADDRESSKeyword_0_3() { return cADDRESSKeyword_0_3; }
		
		//identifier=ID
		public Assignment getIdentifierAssignment_0_4() { return cIdentifierAssignment_0_4; }
		
		//ID
		public RuleCall getIdentifierIDTerminalRuleCall_0_4_0() { return cIdentifierIDTerminalRuleCall_0_4_0; }
		
		//'UNSAFE'? 'PATTERN' Header 'ADDRESS' identifier=ID
		public Group getGroup_1() { return cGroup_1; }
		
		//'UNSAFE'?
		public Keyword getUNSAFEKeyword_1_0() { return cUNSAFEKeyword_1_0; }
		
		//'PATTERN'
		public Keyword getPATTERNKeyword_1_1() { return cPATTERNKeyword_1_1; }
		
		//Header
		public RuleCall getHeaderParserRuleCall_1_2() { return cHeaderParserRuleCall_1_2; }
		
		//'ADDRESS'
		public Keyword getADDRESSKeyword_1_3() { return cADDRESSKeyword_1_3; }
		
		//identifier=ID
		public Assignment getIdentifierAssignment_1_4() { return cIdentifierAssignment_1_4; }
		
		//ID
		public RuleCall getIdentifierIDTerminalRuleCall_1_4_0() { return cIdentifierIDTerminalRuleCall_1_4_0; }
		
		//('INLINE' | 'UNSAFE')? 'FUNCTION' Header stm1+=Statement* 'END' name=Name
		public Group getGroup_2() { return cGroup_2; }
		
		//('INLINE' | 'UNSAFE')?
		public Alternatives getAlternatives_2_0() { return cAlternatives_2_0; }
		
		//'INLINE'
		public Keyword getINLINEKeyword_2_0_0() { return cINLINEKeyword_2_0_0; }
		
		//'UNSAFE'
		public Keyword getUNSAFEKeyword_2_0_1() { return cUNSAFEKeyword_2_0_1; }
		
		//'FUNCTION'
		public Keyword getFUNCTIONKeyword_2_1() { return cFUNCTIONKeyword_2_1; }
		
		//Header
		public RuleCall getHeaderParserRuleCall_2_2() { return cHeaderParserRuleCall_2_2; }
		
		//stm1+=Statement*
		public Assignment getStm1Assignment_2_3() { return cStm1Assignment_2_3; }
		
		//Statement
		public RuleCall getStm1StatementParserRuleCall_2_3_0() { return cStm1StatementParserRuleCall_2_3_0; }
		
		//'END'
		public Keyword getENDKeyword_2_4() { return cENDKeyword_2_4; }
		
		//name=Name
		public Assignment getNameAssignment_2_5() { return cNameAssignment_2_5; }
		
		//Name
		public RuleCall getNameNameParserRuleCall_2_5_0() { return cNameNameParserRuleCall_2_5_0; }
		
		//'FACTORY' Header stm2+=Statement* 'END' name=Name
		public Group getGroup_3() { return cGroup_3; }
		
		//'FACTORY'
		public Keyword getFACTORYKeyword_3_0() { return cFACTORYKeyword_3_0; }
		
		//Header
		public RuleCall getHeaderParserRuleCall_3_1() { return cHeaderParserRuleCall_3_1; }
		
		//stm2+=Statement*
		public Assignment getStm2Assignment_3_2() { return cStm2Assignment_3_2; }
		
		//Statement
		public RuleCall getStm2StatementParserRuleCall_3_2_0() { return cStm2StatementParserRuleCall_3_2_0; }
		
		//'END'
		public Keyword getENDKeyword_3_3() { return cENDKeyword_3_3; }
		
		//name=Name
		public Assignment getNameAssignment_3_4() { return cNameAssignment_3_4; }
		
		//Name
		public RuleCall getNameNameParserRuleCall_3_4_0() { return cNameNameParserRuleCall_3_4_0; }
	}
	public class HelpinfoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.trabalho.MAL.Helpinfo");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCOMMENTKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cString_literalAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cString_literalSTRINGTerminalRuleCall_1_0 = (RuleCall)cString_literalAssignment_1.eContents().get(0);
		
		//Helpinfo:
		//	'COMMENT' string_literal=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//'COMMENT' string_literal=STRING
		public Group getGroup() { return cGroup; }
		
		//'COMMENT'
		public Keyword getCOMMENTKeyword_0() { return cCOMMENTKeyword_0; }
		
		//string_literal=STRING
		public Assignment getString_literalAssignment_1() { return cString_literalAssignment_1; }
		
		//STRING
		public RuleCall getString_literalSTRINGTerminalRuleCall_1_0() { return cString_literalSTRINGTerminalRuleCall_1_0; }
	}
	public class HeaderElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.trabalho.MAL.Header");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cNameParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cParamAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cParamParamsParserRuleCall_2_0 = (RuleCall)cParamAssignment_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cResultAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cResultResultParserRuleCall_4_0 = (RuleCall)cResultAssignment_4.eContents().get(0);
		
		//Header:
		//	Name '(' param=Params ')' result=Result;
		@Override public ParserRule getRule() { return rule; }
		
		//Name '(' param=Params ')' result=Result
		public Group getGroup() { return cGroup; }
		
		//Name
		public RuleCall getNameParserRuleCall_0() { return cNameParserRuleCall_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//param=Params
		public Assignment getParamAssignment_2() { return cParamAssignment_2; }
		
		//Params
		public RuleCall getParamParamsParserRuleCall_2_0() { return cParamParamsParserRuleCall_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
		
		//result=Result
		public Assignment getResultAssignment_4() { return cResultAssignment_4; }
		
		//Result
		public RuleCall getResultResultParserRuleCall_4_0() { return cResultResultParserRuleCall_4_0; }
	}
	public class NameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.trabalho.MAL.Name");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Group cGroup_0_0 = (Group)cGroup_0.eContents().get(0);
		private final Assignment cMnAssignment_0_0_0 = (Assignment)cGroup_0_0.eContents().get(0);
		private final RuleCall cMnModuleNameParserRuleCall_0_0_0_0 = (RuleCall)cMnAssignment_0_0_0.eContents().get(0);
		private final Keyword cFullStopKeyword_0_0_1 = (Keyword)cGroup_0_0.eContents().get(1);
		private final Assignment cIdAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cIdIDTerminalRuleCall_0_1_0 = (RuleCall)cIdAssignment_0_1.eContents().get(0);
		private final Assignment cIdAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cIdIDTerminalRuleCall_1_0 = (RuleCall)cIdAssignment_1.eContents().get(0);
		
		//Name:
		//	(mn+=ModuleName '.')* id=ID | id=ID // TODO: Descobrir o que é ModuleName
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//(mn+=ModuleName '.')* id=ID | id=ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//(mn+=ModuleName '.')* id=ID
		public Group getGroup_0() { return cGroup_0; }
		
		//(mn+=ModuleName '.')*
		public Group getGroup_0_0() { return cGroup_0_0; }
		
		//mn+=ModuleName
		public Assignment getMnAssignment_0_0_0() { return cMnAssignment_0_0_0; }
		
		//ModuleName
		public RuleCall getMnModuleNameParserRuleCall_0_0_0_0() { return cMnModuleNameParserRuleCall_0_0_0_0; }
		
		//'.'
		public Keyword getFullStopKeyword_0_0_1() { return cFullStopKeyword_0_0_1; }
		
		//id=ID
		public Assignment getIdAssignment_0_1() { return cIdAssignment_0_1; }
		
		//ID
		public RuleCall getIdIDTerminalRuleCall_0_1_0() { return cIdIDTerminalRuleCall_0_1_0; }
		
		//id=ID
		public Assignment getIdAssignment_1() { return cIdAssignment_1; }
		
		//ID
		public RuleCall getIdIDTerminalRuleCall_1_0() { return cIdIDTerminalRuleCall_1_0; }
	}
	public class ResultElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.trabalho.MAL.Result");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cTypeNameParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cParamsParserRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		
		//Result:
		//	TypeName | '(' Params ')';
		@Override public ParserRule getRule() { return rule; }
		
		//TypeName | '(' Params ')'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//TypeName
		public RuleCall getTypeNameParserRuleCall_0() { return cTypeNameParserRuleCall_0; }
		
		//'(' Params ')'
		public Group getGroup_1() { return cGroup_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1_0() { return cLeftParenthesisKeyword_1_0; }
		
		//Params
		public RuleCall getParamsParserRuleCall_1_1() { return cParamsParserRuleCall_1_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_1_2() { return cRightParenthesisKeyword_1_2; }
	}
	public class ParamsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.trabalho.MAL.Params");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cBindingParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cCommaKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cBindAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cBindBindingParserRuleCall_1_1_0 = (RuleCall)cBindAssignment_1_1.eContents().get(0);
		
		//Params:
		//	Binding (',' bind+=Binding)*;
		@Override public ParserRule getRule() { return rule; }
		
		//Binding (',' bind+=Binding)*
		public Group getGroup() { return cGroup; }
		
		//Binding
		public RuleCall getBindingParserRuleCall_0() { return cBindingParserRuleCall_0; }
		
		//(',' bind+=Binding)*
		public Group getGroup_1() { return cGroup_1; }
		
		//','
		public Keyword getCommaKeyword_1_0() { return cCommaKeyword_1_0; }
		
		//bind+=Binding
		public Assignment getBindAssignment_1_1() { return cBindAssignment_1_1; }
		
		//Binding
		public RuleCall getBindBindingParserRuleCall_1_1_0() { return cBindBindingParserRuleCall_1_1_0; }
	}
	public class BindingElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.trabalho.MAL.Binding");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cIdentifierAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cIdentifierIDTerminalRuleCall_0_0 = (RuleCall)cIdentifierAssignment_0.eContents().get(0);
		private final Assignment cTnAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTnTypeNameParserRuleCall_1_0 = (RuleCall)cTnAssignment_1.eContents().get(0);
		
		//Binding:
		//	identifier=ID tn=TypeName;
		@Override public ParserRule getRule() { return rule; }
		
		//identifier=ID tn=TypeName
		public Group getGroup() { return cGroup; }
		
		//identifier=ID
		public Assignment getIdentifierAssignment_0() { return cIdentifierAssignment_0; }
		
		//ID
		public RuleCall getIdentifierIDTerminalRuleCall_0_0() { return cIdentifierIDTerminalRuleCall_0_0; }
		
		//tn=TypeName
		public Assignment getTnAssignment_1() { return cTnAssignment_1; }
		
		//TypeName
		public RuleCall getTnTypeNameParserRuleCall_1_0() { return cTnTypeNameParserRuleCall_1_0; }
	}
	public class TypeNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.trabalho.MAL.TypeName");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cScalarTypeParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cColumnTypeParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Keyword cColonKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cAtAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cAtAnyTypeParserRuleCall_2_1_0 = (RuleCall)cAtAssignment_2_1.eContents().get(0);
		
		//TypeName:
		//	ScalarType | ColumnType | ':' at=AnyType // TODO: any e digit são ID???? 
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//ScalarType | ColumnType | ':' at=AnyType
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//ScalarType
		public RuleCall getScalarTypeParserRuleCall_0() { return cScalarTypeParserRuleCall_0; }
		
		//ColumnType
		public RuleCall getColumnTypeParserRuleCall_1() { return cColumnTypeParserRuleCall_1; }
		
		//':' at=AnyType
		public Group getGroup_2() { return cGroup_2; }
		
		//':'
		public Keyword getColonKeyword_2_0() { return cColonKeyword_2_0; }
		
		//at=AnyType
		public Assignment getAtAssignment_2_1() { return cAtAssignment_2_1; }
		
		//AnyType
		public RuleCall getAtAnyTypeParserRuleCall_2_1_0() { return cAtAnyTypeParserRuleCall_2_1_0; }
	}
	public class ScalarTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.trabalho.MAL.ScalarType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cColonKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cIdentifierAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cIdentifierIDTerminalRuleCall_1_0 = (RuleCall)cIdentifierAssignment_1.eContents().get(0);
		
		//ScalarType:
		//	':' identifier=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//':' identifier=ID
		public Group getGroup() { return cGroup; }
		
		//':'
		public Keyword getColonKeyword_0() { return cColonKeyword_0; }
		
		//identifier=ID
		public Assignment getIdentifierAssignment_1() { return cIdentifierAssignment_1; }
		
		//ID
		public RuleCall getIdentifierIDTerminalRuleCall_1_0() { return cIdentifierIDTerminalRuleCall_1_0; }
	}
	public class ColumnTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.trabalho.MAL.ColumnType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cColonKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cBATKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final RuleCall cColElmTypeParserRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		private final Keyword cRightSquareBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//ColumnType:
		//	':' 'BAT' '[' ':' ColElmType ']';
		@Override public ParserRule getRule() { return rule; }
		
		//':' 'BAT' '[' ':' ColElmType ']'
		public Group getGroup() { return cGroup; }
		
		//':'
		public Keyword getColonKeyword_0() { return cColonKeyword_0; }
		
		//'BAT'
		public Keyword getBATKeyword_1() { return cBATKeyword_1; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_2() { return cLeftSquareBracketKeyword_2; }
		
		//':'
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }
		
		//ColElmType
		public RuleCall getColElmTypeParserRuleCall_4() { return cColElmTypeParserRuleCall_4; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_5() { return cRightSquareBracketKeyword_5; }
	}
	public class ColElmTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.trabalho.MAL.ColElmType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cScalarTypeParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cAnyTypeParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//ColElmType:
		//	ScalarType | AnyType // TODO: Descobrir o que é AnyType
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//ScalarType | AnyType
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//ScalarType
		public RuleCall getScalarTypeParserRuleCall_0() { return cScalarTypeParserRuleCall_0; }
		
		//AnyType
		public RuleCall getAnyTypeParserRuleCall_1() { return cAnyTypeParserRuleCall_1; }
	}
	public class AnyTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.trabalho.MAL.AnyType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cAnyTypeAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cAnyKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword c_Keyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cDigitAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cDigitIDTerminalRuleCall_2_1_0 = (RuleCall)cDigitAssignment_2_1.eContents().get(0);
		
		//AnyType:
		//	{AnyType} 'any' ('_' digit=ID)?;
		@Override public ParserRule getRule() { return rule; }
		
		//{AnyType} 'any' ('_' digit=ID)?
		public Group getGroup() { return cGroup; }
		
		//{AnyType}
		public Action getAnyTypeAction_0() { return cAnyTypeAction_0; }
		
		//'any'
		public Keyword getAnyKeyword_1() { return cAnyKeyword_1; }
		
		//('_' digit=ID)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'_'
		public Keyword get_Keyword_2_0() { return c_Keyword_2_0; }
		
		//digit=ID
		public Assignment getDigitAssignment_2_1() { return cDigitAssignment_2_1; }
		
		//ID
		public RuleCall getDigitIDTerminalRuleCall_2_1_0() { return cDigitIDTerminalRuleCall_2_1_0; }
	}
	public class StmtElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.trabalho.MAL.Stmt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cFlowParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final RuleCall cVarlistParserRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cColonEqualsSignKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cExpAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cExpExprParserRuleCall_2_1_0 = (RuleCall)cExpAssignment_2_1.eContents().get(0);
		
		//Stmt:
		//	Flow? Varlist (':=' exp=Expr);
		@Override public ParserRule getRule() { return rule; }
		
		//Flow? Varlist (':=' exp=Expr)
		public Group getGroup() { return cGroup; }
		
		//Flow?
		public RuleCall getFlowParserRuleCall_0() { return cFlowParserRuleCall_0; }
		
		//Varlist
		public RuleCall getVarlistParserRuleCall_1() { return cVarlistParserRuleCall_1; }
		
		//':=' exp=Expr
		public Group getGroup_2() { return cGroup_2; }
		
		//':='
		public Keyword getColonEqualsSignKeyword_2_0() { return cColonEqualsSignKeyword_2_0; }
		
		//exp=Expr
		public Assignment getExpAssignment_2_1() { return cExpAssignment_2_1; }
		
		//Expr
		public RuleCall getExpExprParserRuleCall_2_1_0() { return cExpExprParserRuleCall_2_1_0; }
	}
	public class FlowElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.trabalho.MAL.Flow");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cRETURNKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cBARRIERKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cCATCHKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		private final Keyword cLEAVEKeyword_3 = (Keyword)cAlternatives.eContents().get(3);
		private final Keyword cREDOKeyword_4 = (Keyword)cAlternatives.eContents().get(4);
		private final Keyword cRAISEKeyword_5 = (Keyword)cAlternatives.eContents().get(5);
		
		//Flow:
		//	'RETURN' | 'BARRIER' | 'CATCH' | 'LEAVE' | 'REDO' | 'RAISE';
		@Override public ParserRule getRule() { return rule; }
		
		//'RETURN' | 'BARRIER' | 'CATCH' | 'LEAVE' | 'REDO' | 'RAISE'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'RETURN'
		public Keyword getRETURNKeyword_0() { return cRETURNKeyword_0; }
		
		//'BARRIER'
		public Keyword getBARRIERKeyword_1() { return cBARRIERKeyword_1; }
		
		//'CATCH'
		public Keyword getCATCHKeyword_2() { return cCATCHKeyword_2; }
		
		//'LEAVE'
		public Keyword getLEAVEKeyword_3() { return cLEAVEKeyword_3; }
		
		//'REDO'
		public Keyword getREDOKeyword_4() { return cREDOKeyword_4; }
		
		//'RAISE'
		public Keyword getRAISEKeyword_5() { return cRAISEKeyword_5; }
	}
	public class VarlistElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.trabalho.MAL.Varlist");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cVariableParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cVariableParserRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final Group cGroup_1_2 = (Group)cGroup_1.eContents().get(2);
		private final Keyword cCommaKeyword_1_2_0 = (Keyword)cGroup_1_2.eContents().get(0);
		private final Assignment cVar1Assignment_1_2_1 = (Assignment)cGroup_1_2.eContents().get(1);
		private final RuleCall cVar1VariableParserRuleCall_1_2_1_0 = (RuleCall)cVar1Assignment_1_2_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_1_3 = (Keyword)cGroup_1.eContents().get(3);
		
		//Varlist:
		//	Variable | '(' Variable (',' var1+=Variable)* ')';
		@Override public ParserRule getRule() { return rule; }
		
		//Variable | '(' Variable (',' var1+=Variable)* ')'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Variable
		public RuleCall getVariableParserRuleCall_0() { return cVariableParserRuleCall_0; }
		
		//'(' Variable (',' var1+=Variable)* ')'
		public Group getGroup_1() { return cGroup_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1_0() { return cLeftParenthesisKeyword_1_0; }
		
		//Variable
		public RuleCall getVariableParserRuleCall_1_1() { return cVariableParserRuleCall_1_1; }
		
		//(',' var1+=Variable)*
		public Group getGroup_1_2() { return cGroup_1_2; }
		
		//','
		public Keyword getCommaKeyword_1_2_0() { return cCommaKeyword_1_2_0; }
		
		//var1+=Variable
		public Assignment getVar1Assignment_1_2_1() { return cVar1Assignment_1_2_1; }
		
		//Variable
		public RuleCall getVar1VariableParserRuleCall_1_2_1_0() { return cVar1VariableParserRuleCall_1_2_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_1_3() { return cRightParenthesisKeyword_1_3; }
	}
	public class VariableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.trabalho.MAL.Variable");
		private final Assignment cIdentifierAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cIdentifierIDTerminalRuleCall_0 = (RuleCall)cIdentifierAssignment.eContents().get(0);
		
		//Variable:
		//	identifier=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//identifier=ID
		public Assignment getIdentifierAssignment() { return cIdentifierAssignment; }
		
		//ID
		public RuleCall getIdentifierIDTerminalRuleCall_0() { return cIdentifierIDTerminalRuleCall_0; }
	}
	public class ExprElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.trabalho.MAL.Expr");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cFcncallParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Group cGroup_1_0 = (Group)cGroup_1.eContents().get(0);
		private final Assignment cF1Assignment_1_0_0 = (Assignment)cGroup_1_0.eContents().get(0);
		private final RuleCall cF1FactorParserRuleCall_1_0_0_0 = (RuleCall)cF1Assignment_1_0_0.eContents().get(0);
		private final RuleCall cOperatorParserRuleCall_1_0_1 = (RuleCall)cGroup_1_0.eContents().get(1);
		private final Assignment cF2Assignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cF2FactorParserRuleCall_1_1_0 = (RuleCall)cF2Assignment_1_1.eContents().get(0);
		
		//Expr:
		//	Fcncall | (f1=Factor Operator)? f2=Factor // TODO: operator é ID????
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//Fcncall | (f1=Factor Operator)? f2=Factor
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Fcncall
		public RuleCall getFcncallParserRuleCall_0() { return cFcncallParserRuleCall_0; }
		
		//(f1=Factor Operator)? f2=Factor
		public Group getGroup_1() { return cGroup_1; }
		
		//(f1=Factor Operator)?
		public Group getGroup_1_0() { return cGroup_1_0; }
		
		//f1=Factor
		public Assignment getF1Assignment_1_0_0() { return cF1Assignment_1_0_0; }
		
		//Factor
		public RuleCall getF1FactorParserRuleCall_1_0_0_0() { return cF1FactorParserRuleCall_1_0_0_0; }
		
		//Operator
		public RuleCall getOperatorParserRuleCall_1_0_1() { return cOperatorParserRuleCall_1_0_1; }
		
		//f2=Factor
		public Assignment getF2Assignment_1_1() { return cF2Assignment_1_1; }
		
		//Factor
		public RuleCall getF2FactorParserRuleCall_1_1_0() { return cF2FactorParserRuleCall_1_1_0; }
	}
	public class OperatorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.trabalho.MAL.Operator");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cPlusSignKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cHyphenMinusKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cAsteriskKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		private final Keyword cSolidusKeyword_3 = (Keyword)cAlternatives.eContents().get(3);
		private final Keyword cAmpersandAmpersandKeyword_4 = (Keyword)cAlternatives.eContents().get(4);
		private final Keyword cVerticalLineVerticalLineKeyword_5 = (Keyword)cAlternatives.eContents().get(5);
		
		//Operator:
		//	'+' | '-' | '*' | '/' | '&&' | "||";
		@Override public ParserRule getRule() { return rule; }
		
		//'+' | '-' | '*' | '/' | '&&' | "||"
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'+'
		public Keyword getPlusSignKeyword_0() { return cPlusSignKeyword_0; }
		
		//'-'
		public Keyword getHyphenMinusKeyword_1() { return cHyphenMinusKeyword_1; }
		
		//'*'
		public Keyword getAsteriskKeyword_2() { return cAsteriskKeyword_2; }
		
		//'/'
		public Keyword getSolidusKeyword_3() { return cSolidusKeyword_3; }
		
		//'&&'
		public Keyword getAmpersandAmpersandKeyword_4() { return cAmpersandAmpersandKeyword_4; }
		
		//"||"
		public Keyword getVerticalLineVerticalLineKeyword_5() { return cVerticalLineVerticalLineKeyword_5; }
	}
	public class FactorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.trabalho.MAL.Factor");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFactorAction_0 = (Action)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Assignment cLtAssignment_1_0 = (Assignment)cAlternatives_1.eContents().get(0);
		private final RuleCall cLtLiteral_constantParserRuleCall_1_0_0 = (RuleCall)cLtAssignment_1_0.eContents().get(0);
		private final Keyword cNILKeyword_1_1 = (Keyword)cAlternatives_1.eContents().get(1);
		private final Assignment cVarAssignment_1_2 = (Assignment)cAlternatives_1.eContents().get(2);
		private final RuleCall cVarVariableParserRuleCall_1_2_0 = (RuleCall)cVarAssignment_1_2.eContents().get(0);
		
		//Factor:
		//	{Factor} (lt=Literal_constant | 'NIL' | var=Variable);
		@Override public ParserRule getRule() { return rule; }
		
		//{Factor} (lt=Literal_constant | 'NIL' | var=Variable)
		public Group getGroup() { return cGroup; }
		
		//{Factor}
		public Action getFactorAction_0() { return cFactorAction_0; }
		
		//lt=Literal_constant | 'NIL' | var=Variable
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//lt=Literal_constant
		public Assignment getLtAssignment_1_0() { return cLtAssignment_1_0; }
		
		//Literal_constant
		public RuleCall getLtLiteral_constantParserRuleCall_1_0_0() { return cLtLiteral_constantParserRuleCall_1_0_0; }
		
		//'NIL'
		public Keyword getNILKeyword_1_1() { return cNILKeyword_1_1; }
		
		//var=Variable
		public Assignment getVarAssignment_1_2() { return cVarAssignment_1_2; }
		
		//Variable
		public RuleCall getVarVariableParserRuleCall_1_2_0() { return cVarVariableParserRuleCall_1_2_0; }
	}
	public class FcncallElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.trabalho.MAL.Fcncall");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cModuleNameParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Keyword cFullStopKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameNameParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cArgsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cArgsArgsParserRuleCall_4_0 = (RuleCall)cArgsAssignment_4.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Fcncall:
		//	ModuleName '.' name=Name '(' args=Args? ')' // TODO: Descobrir o que é ModuleName
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//ModuleName '.' name=Name '(' args=Args? ')'
		public Group getGroup() { return cGroup; }
		
		//ModuleName
		public RuleCall getModuleNameParserRuleCall_0() { return cModuleNameParserRuleCall_0; }
		
		//'.'
		public Keyword getFullStopKeyword_1() { return cFullStopKeyword_1; }
		
		//name=Name
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//Name
		public RuleCall getNameNameParserRuleCall_2_0() { return cNameNameParserRuleCall_2_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_3() { return cLeftParenthesisKeyword_3; }
		
		//args=Args?
		public Assignment getArgsAssignment_4() { return cArgsAssignment_4; }
		
		//Args
		public RuleCall getArgsArgsParserRuleCall_4_0() { return cArgsArgsParserRuleCall_4_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5() { return cRightParenthesisKeyword_5; }
	}
	public class ArgsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.trabalho.MAL.Args");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cF1Assignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cF1FactorParserRuleCall_0_0 = (RuleCall)cF1Assignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cCommaKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cFactor2Assignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cFactor2FactorParserRuleCall_1_1_0 = (RuleCall)cFactor2Assignment_1_1.eContents().get(0);
		
		//Args:
		//	f1=Factor (',' factor2+=Factor)*;
		@Override public ParserRule getRule() { return rule; }
		
		//f1=Factor (',' factor2+=Factor)*
		public Group getGroup() { return cGroup; }
		
		//f1=Factor
		public Assignment getF1Assignment_0() { return cF1Assignment_0; }
		
		//Factor
		public RuleCall getF1FactorParserRuleCall_0_0() { return cF1FactorParserRuleCall_0_0; }
		
		//(',' factor2+=Factor)*
		public Group getGroup_1() { return cGroup_1; }
		
		//','
		public Keyword getCommaKeyword_1_0() { return cCommaKeyword_1_0; }
		
		//factor2+=Factor
		public Assignment getFactor2Assignment_1_1() { return cFactor2Assignment_1_1; }
		
		//Factor
		public RuleCall getFactor2FactorParserRuleCall_1_1_0() { return cFactor2FactorParserRuleCall_1_1_0; }
	}
	public class ModuleNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.trabalho.MAL.ModuleName");
		private final Assignment cIdentifierAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cIdentifierIDTerminalRuleCall_0 = (RuleCall)cIdentifierAssignment.eContents().get(0);
		
		//ModuleName:
		//	identifier=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//identifier=ID
		public Assignment getIdentifierAssignment() { return cIdentifierAssignment; }
		
		//ID
		public RuleCall getIdentifierIDTerminalRuleCall_0() { return cIdentifierIDTerminalRuleCall_0; }
	}
	public class Literal_constantElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.trabalho.MAL.Literal_constant");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cBITTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cBteParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cCHRTerminalRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cWRDTerminalRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cINTTerminalRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cOIDTerminalRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cFLTParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		private final RuleCall cSTRParserRuleCall_7 = (RuleCall)cAlternatives.eContents().get(7);
		
		//Literal_constant:
		//	BIT | Bte | CHR | WRD | INT | OID | FLT | STR //| Sht | DBL | LNG
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//BIT | Bte | CHR | WRD | INT | OID | FLT | STR
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//BIT
		public RuleCall getBITTerminalRuleCall_0() { return cBITTerminalRuleCall_0; }
		
		//Bte
		public RuleCall getBteParserRuleCall_1() { return cBteParserRuleCall_1; }
		
		//CHR
		public RuleCall getCHRTerminalRuleCall_2() { return cCHRTerminalRuleCall_2; }
		
		//WRD
		public RuleCall getWRDTerminalRuleCall_3() { return cWRDTerminalRuleCall_3; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_4() { return cINTTerminalRuleCall_4; }
		
		//OID
		public RuleCall getOIDTerminalRuleCall_5() { return cOIDTerminalRuleCall_5; }
		
		//FLT
		public RuleCall getFLTParserRuleCall_6() { return cFLTParserRuleCall_6; }
		
		//STR
		public RuleCall getSTRParserRuleCall_7() { return cSTRParserRuleCall_7; }
	}
	public class BteElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.trabalho.MAL.Bte");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cBITTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final RuleCall cBITTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final RuleCall cBITTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final RuleCall cBITTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final RuleCall cBITTerminalRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		private final RuleCall cBITTerminalRuleCall_5 = (RuleCall)cGroup.eContents().get(5);
		private final RuleCall cBITTerminalRuleCall_6 = (RuleCall)cGroup.eContents().get(6);
		private final RuleCall cBITTerminalRuleCall_7 = (RuleCall)cGroup.eContents().get(7);
		
		//Bte:
		//	BIT BIT BIT BIT BIT BIT BIT BIT;
		@Override public ParserRule getRule() { return rule; }
		
		//BIT BIT BIT BIT BIT BIT BIT BIT
		public Group getGroup() { return cGroup; }
		
		//BIT
		public RuleCall getBITTerminalRuleCall_0() { return cBITTerminalRuleCall_0; }
		
		//BIT
		public RuleCall getBITTerminalRuleCall_1() { return cBITTerminalRuleCall_1; }
		
		//BIT
		public RuleCall getBITTerminalRuleCall_2() { return cBITTerminalRuleCall_2; }
		
		//BIT
		public RuleCall getBITTerminalRuleCall_3() { return cBITTerminalRuleCall_3; }
		
		//BIT
		public RuleCall getBITTerminalRuleCall_4() { return cBITTerminalRuleCall_4; }
		
		//BIT
		public RuleCall getBITTerminalRuleCall_5() { return cBITTerminalRuleCall_5; }
		
		//BIT
		public RuleCall getBITTerminalRuleCall_6() { return cBITTerminalRuleCall_6; }
		
		//BIT
		public RuleCall getBITTerminalRuleCall_7() { return cBITTerminalRuleCall_7; }
	}
	public class FLTElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.trabalho.MAL.FLT");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Keyword cFullStopKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		
		//FLT:
		//	INT '.' INT;
		@Override public ParserRule getRule() { return rule; }
		
		//INT '.' INT
		public Group getGroup() { return cGroup; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_0() { return cINTTerminalRuleCall_0; }
		
		//'.'
		public Keyword getFullStopKeyword_1() { return cFullStopKeyword_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_2() { return cINTTerminalRuleCall_2; }
	}
	public class STRElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.trabalho.MAL.STR");
		private final RuleCall cSTRINGTerminalRuleCall = (RuleCall)rule.eContents().get(1);
		
		//STR:
		//	STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall() { return cSTRINGTerminalRuleCall; }
	}
	
	
	private final ProgramElements pProgram;
	private final StatementElements pStatement;
	private final ModuleStmtElements pModuleStmt;
	private final IncludeStmtElements pIncludeStmt;
	private final DefinitionElements pDefinition;
	private final HelpinfoElements pHelpinfo;
	private final HeaderElements pHeader;
	private final NameElements pName;
	private final ResultElements pResult;
	private final ParamsElements pParams;
	private final BindingElements pBinding;
	private final TypeNameElements pTypeName;
	private final ScalarTypeElements pScalarType;
	private final ColumnTypeElements pColumnType;
	private final ColElmTypeElements pColElmType;
	private final AnyTypeElements pAnyType;
	private final StmtElements pStmt;
	private final FlowElements pFlow;
	private final VarlistElements pVarlist;
	private final VariableElements pVariable;
	private final ExprElements pExpr;
	private final OperatorElements pOperator;
	private final FactorElements pFactor;
	private final FcncallElements pFcncall;
	private final ArgsElements pArgs;
	private final ModuleNameElements pModuleName;
	private final Literal_constantElements pLiteral_constant;
	private final TerminalRule tBIT;
	private final BteElements pBte;
	private final TerminalRule tCHR;
	private final TerminalRule tWRD;
	private final TerminalRule tOID;
	private final FLTElements pFLT;
	private final STRElements pSTR;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MALGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pProgram = new ProgramElements();
		this.pStatement = new StatementElements();
		this.pModuleStmt = new ModuleStmtElements();
		this.pIncludeStmt = new IncludeStmtElements();
		this.pDefinition = new DefinitionElements();
		this.pHelpinfo = new HelpinfoElements();
		this.pHeader = new HeaderElements();
		this.pName = new NameElements();
		this.pResult = new ResultElements();
		this.pParams = new ParamsElements();
		this.pBinding = new BindingElements();
		this.pTypeName = new TypeNameElements();
		this.pScalarType = new ScalarTypeElements();
		this.pColumnType = new ColumnTypeElements();
		this.pColElmType = new ColElmTypeElements();
		this.pAnyType = new AnyTypeElements();
		this.pStmt = new StmtElements();
		this.pFlow = new FlowElements();
		this.pVarlist = new VarlistElements();
		this.pVariable = new VariableElements();
		this.pExpr = new ExprElements();
		this.pOperator = new OperatorElements();
		this.pFactor = new FactorElements();
		this.pFcncall = new FcncallElements();
		this.pArgs = new ArgsElements();
		this.pModuleName = new ModuleNameElements();
		this.pLiteral_constant = new Literal_constantElements();
		this.tBIT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.trabalho.MAL.BIT");
		this.pBte = new BteElements();
		this.tCHR = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.trabalho.MAL.CHR");
		this.tWRD = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.trabalho.MAL.WRD");
		this.tOID = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.trabalho.MAL.OID");
		this.pFLT = new FLTElements();
		this.pSTR = new STRElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.trabalho.MAL".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Program:
	//	(elements+=Statement ';')*;
	public ProgramElements getProgramAccess() {
		return pProgram;
	}
	
	public ParserRule getProgramRule() {
		return getProgramAccess().getRule();
	}
	
	//Statement:
	//	ModuleStmt help=Helpinfo? | Definition help=Helpinfo? | IncludeStmt | Stmt;
	public StatementElements getStatementAccess() {
		return pStatement;
	}
	
	public ParserRule getStatementRule() {
		return getStatementAccess().getRule();
	}
	
	//ModuleStmt:
	//	'MODULE' ident=ID | 'ATOM' ident1=ID (':' ident2=ID)?;
	public ModuleStmtElements getModuleStmtAccess() {
		return pModuleStmt;
	}
	
	public ParserRule getModuleStmtRule() {
		return getModuleStmtAccess().getRule();
	}
	
	//IncludeStmt:
	//	'INCLUDE' identifier=ID | 'INCLUDE' string_literal=STRING;
	public IncludeStmtElements getIncludeStmtAccess() {
		return pIncludeStmt;
	}
	
	public ParserRule getIncludeStmtRule() {
		return getIncludeStmtAccess().getRule();
	}
	
	//Definition:
	//	'UNSAFE'? 'COMMAND' Header 'ADDRESS' identifier=ID | 'UNSAFE'? 'PATTERN' Header 'ADDRESS' identifier=ID | ('INLINE' |
	//	'UNSAFE')? 'FUNCTION' Header stm1+=Statement* 'END' name=Name |
	//	'FACTORY' Header stm2+=Statement* 'END' name=Name;
	public DefinitionElements getDefinitionAccess() {
		return pDefinition;
	}
	
	public ParserRule getDefinitionRule() {
		return getDefinitionAccess().getRule();
	}
	
	//Helpinfo:
	//	'COMMENT' string_literal=STRING;
	public HelpinfoElements getHelpinfoAccess() {
		return pHelpinfo;
	}
	
	public ParserRule getHelpinfoRule() {
		return getHelpinfoAccess().getRule();
	}
	
	//Header:
	//	Name '(' param=Params ')' result=Result;
	public HeaderElements getHeaderAccess() {
		return pHeader;
	}
	
	public ParserRule getHeaderRule() {
		return getHeaderAccess().getRule();
	}
	
	//Name:
	//	(mn+=ModuleName '.')* id=ID | id=ID // TODO: Descobrir o que é ModuleName
	//;
	public NameElements getNameAccess() {
		return pName;
	}
	
	public ParserRule getNameRule() {
		return getNameAccess().getRule();
	}
	
	//Result:
	//	TypeName | '(' Params ')';
	public ResultElements getResultAccess() {
		return pResult;
	}
	
	public ParserRule getResultRule() {
		return getResultAccess().getRule();
	}
	
	//Params:
	//	Binding (',' bind+=Binding)*;
	public ParamsElements getParamsAccess() {
		return pParams;
	}
	
	public ParserRule getParamsRule() {
		return getParamsAccess().getRule();
	}
	
	//Binding:
	//	identifier=ID tn=TypeName;
	public BindingElements getBindingAccess() {
		return pBinding;
	}
	
	public ParserRule getBindingRule() {
		return getBindingAccess().getRule();
	}
	
	//TypeName:
	//	ScalarType | ColumnType | ':' at=AnyType // TODO: any e digit são ID???? 
	//;
	public TypeNameElements getTypeNameAccess() {
		return pTypeName;
	}
	
	public ParserRule getTypeNameRule() {
		return getTypeNameAccess().getRule();
	}
	
	//ScalarType:
	//	':' identifier=ID;
	public ScalarTypeElements getScalarTypeAccess() {
		return pScalarType;
	}
	
	public ParserRule getScalarTypeRule() {
		return getScalarTypeAccess().getRule();
	}
	
	//ColumnType:
	//	':' 'BAT' '[' ':' ColElmType ']';
	public ColumnTypeElements getColumnTypeAccess() {
		return pColumnType;
	}
	
	public ParserRule getColumnTypeRule() {
		return getColumnTypeAccess().getRule();
	}
	
	//ColElmType:
	//	ScalarType | AnyType // TODO: Descobrir o que é AnyType
	//;
	public ColElmTypeElements getColElmTypeAccess() {
		return pColElmType;
	}
	
	public ParserRule getColElmTypeRule() {
		return getColElmTypeAccess().getRule();
	}
	
	//AnyType:
	//	{AnyType} 'any' ('_' digit=ID)?;
	public AnyTypeElements getAnyTypeAccess() {
		return pAnyType;
	}
	
	public ParserRule getAnyTypeRule() {
		return getAnyTypeAccess().getRule();
	}
	
	//Stmt:
	//	Flow? Varlist (':=' exp=Expr);
	public StmtElements getStmtAccess() {
		return pStmt;
	}
	
	public ParserRule getStmtRule() {
		return getStmtAccess().getRule();
	}
	
	//Flow:
	//	'RETURN' | 'BARRIER' | 'CATCH' | 'LEAVE' | 'REDO' | 'RAISE';
	public FlowElements getFlowAccess() {
		return pFlow;
	}
	
	public ParserRule getFlowRule() {
		return getFlowAccess().getRule();
	}
	
	//Varlist:
	//	Variable | '(' Variable (',' var1+=Variable)* ')';
	public VarlistElements getVarlistAccess() {
		return pVarlist;
	}
	
	public ParserRule getVarlistRule() {
		return getVarlistAccess().getRule();
	}
	
	//Variable:
	//	identifier=ID;
	public VariableElements getVariableAccess() {
		return pVariable;
	}
	
	public ParserRule getVariableRule() {
		return getVariableAccess().getRule();
	}
	
	//Expr:
	//	Fcncall | (f1=Factor Operator)? f2=Factor // TODO: operator é ID????
	//;
	public ExprElements getExprAccess() {
		return pExpr;
	}
	
	public ParserRule getExprRule() {
		return getExprAccess().getRule();
	}
	
	//Operator:
	//	'+' | '-' | '*' | '/' | '&&' | "||";
	public OperatorElements getOperatorAccess() {
		return pOperator;
	}
	
	public ParserRule getOperatorRule() {
		return getOperatorAccess().getRule();
	}
	
	//Factor:
	//	{Factor} (lt=Literal_constant | 'NIL' | var=Variable);
	public FactorElements getFactorAccess() {
		return pFactor;
	}
	
	public ParserRule getFactorRule() {
		return getFactorAccess().getRule();
	}
	
	//Fcncall:
	//	ModuleName '.' name=Name '(' args=Args? ')' // TODO: Descobrir o que é ModuleName
	//;
	public FcncallElements getFcncallAccess() {
		return pFcncall;
	}
	
	public ParserRule getFcncallRule() {
		return getFcncallAccess().getRule();
	}
	
	//Args:
	//	f1=Factor (',' factor2+=Factor)*;
	public ArgsElements getArgsAccess() {
		return pArgs;
	}
	
	public ParserRule getArgsRule() {
		return getArgsAccess().getRule();
	}
	
	//ModuleName:
	//	identifier=ID;
	public ModuleNameElements getModuleNameAccess() {
		return pModuleName;
	}
	
	public ParserRule getModuleNameRule() {
		return getModuleNameAccess().getRule();
	}
	
	//Literal_constant:
	//	BIT | Bte | CHR | WRD | INT | OID | FLT | STR //| Sht | DBL | LNG
	//;
	public Literal_constantElements getLiteral_constantAccess() {
		return pLiteral_constant;
	}
	
	public ParserRule getLiteral_constantRule() {
		return getLiteral_constantAccess().getRule();
	}
	
	//terminal BIT:
	//	'0' | '1';
	public TerminalRule getBITRule() {
		return tBIT;
	}
	
	//Bte:
	//	BIT BIT BIT BIT BIT BIT BIT BIT;
	public BteElements getBteAccess() {
		return pBte;
	}
	
	public ParserRule getBteRule() {
		return getBteAccess().getRule();
	}
	
	//terminal CHR:
	//	'a'..'z' | 'A'..'Z' | '_' | '0'..'9';
	public TerminalRule getCHRRule() {
		return tCHR;
	}
	
	//terminal WRD:
	//	('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getWRDRule() {
		return tWRD;
	}
	
	//terminal OID:
	//	'1'..'9' '0'..'9'*;
	public TerminalRule getOIDRule() {
		return tOID;
	}
	
	//FLT:
	//	INT '.' INT;
	public FLTElements getFLTAccess() {
		return pFLT;
	}
	
	public ParserRule getFLTRule() {
		return getFLTAccess().getRule();
	}
	
	//STR:
	//	STRING;
	public STRElements getSTRAccess() {
		return pSTR;
	}
	
	public ParserRule getSTRRule() {
		return getSTRAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
